---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_distribution }}.yaml"

- name: Inlcude tasks
  include_tasks: "{{ task_name }}"
  loop:
    - install.yml
    - prepare_sudo.yml
  loop_control:
    loop_var: task_name