---
- name: Stat file sudoers file
  stat:
    path: "{{ sudoers_path }}"
  register: sudoer_st

- name: Prepare sudo main config
  ansible.builtin.template:
    src: templates/etc/sudoers.j2
    dest: "{{ sudoers_path }}"
    mode: "u=r,g=r"
  when: not sudoer_st.stat.exists

- name: Prepare sudoers.d ansible managed users config
  ansible.builtin.template:
    src: templates/etc/sudoers.d/sudoersd_tpl.j2
    dest: "{{ sudoersd_path }}"
    mode: "u=r,g=r"

- name: Prepare sudo main config
  ansible.builtin.blockinfile:
    content: "{{ lookup('template', 'templates/etc/sudoers_part.j2') }}"
    dest: "{{ sudoers_path }}"
    state: present
    marker: "# ANSIBLE MAGED BLOCK {mark}"
    backup: yes